name: Test GitHub App token

on:
  workflow_dispatch:

jobs:
  create-contents-with-fine-grained-pat:
    runs-on: ubuntu-latest
    steps:
    - name: Create Contents with Fine-grained personal token
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        DATE=`date '+%Y-%m-%d%H:%M:%S'`
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/naotama2002-org/homebrew-assam/contents/pat-${DATE} \
          -d '{"message":"my commit message","committer":{"name":"naoki","email":"naotama@gmail.com"},"content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'

  create-contents-with-github-app-token:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Create Contents with GitHub App token
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        DATE=`date '+%Y-%m-%d%H:%M:%S'`
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/naotama2002-org/homebrew-assam/contents/github-app-${DATE} \
          -d '{"message":"my commit message","committer":{"name":"naoki","email":"naotama@gmail.com"},"content":"cXkgbmV3IGZpbGUgY29udGVudHM="}'
